##
## Makefile for  in /home/kaso/Documents/rendu/EPITECH/YEAR2/PROJECT/OCAML_2015_amazeing1
## 
## Made by 
## Login   <@epitech.net>
## 
## Started on  Mon Mar 28 16:12:28 2016 
## Last update Sun May  1 01:04:19 2016 Kévin Julien
##

RESULT	:= step4

SOURCES	= maze.ml main.ml

all: nc

byte: bc

re: fclean all

-include OCamlMakefile
